menu:
  Home: /
  Archives: /archives

widgets: 
# - search
- category
- tag
- twitter

excerpt_link: Read More

twitter:
  username: dosman711
  show_replies: false
  tweet_count: 5

facebook: baker.chris
github: dosman711
email: dosman711@gmail.com
about: ".Net developer from Indianapolis, IN"
photo: http://0.gravatar.com/avatar/22d6d44b174c3891d35f99e9cde5a213

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:
